### ISSUE TITLE
Error: 'Message' object has no attribute 'destination'

### ISSUE THREAD

**Issue by Nyaran** [Nyaran/telegram-download-daemon-ng#32]
_Originally posted by @shahram7 in https://github.com/Nyaran/telegram-download-daemon-ng/issues/30#issuecomment-1831573759_

> Hi Luis, i have used this compose file here:
> 
> ```
> version: '3.5'
> 
> services:
>   gluetun:
>     image: qmcgaw/gluetun
>     cap_add:
>       - NET_ADMIN
>     environment:
>       - VPN_SERVICE_PROVIDER=nordvpn
>       - OPENVPN_USER=xxxxxxxxxxxxxxxxxx
>       - OPENVPN_PASSWORD=xxxxxxxxxxxxxxxxxxxxx
>       - SERVER_REGIONS=Netherlands
>     restart: unless-stopped
>   tdd:
> #    image: alfem/telegram-download-daemon:latest
> #    image: nyaran/telegram-download-daemon-ng:main
>     image: nyaran/telegram-download-daemon-ng:1.0.0-beta.6
>     container_name: telegram-download
>     network_mode: service:gluetun
>     depends_on:
>       - gluetun
>     read_only: true
>     environment:
>       - TELEGRAM_DAEMON_API_ID=xxxxxxxxxxxxxxx
>       - TELEGRAM_DAEMON_API_HASH=xxxxxxxxxxxx
>       - TELEGRAM_DAEMON_CHANNEL=-xxxxxxxxxxxxx
>       - TELEGRAM_DAEMON_DEST=/downloads
>       - TELEGRAM_DAEMON_SESSION_PATH=/session
>       - TELEGRAM_DAEMON_DUPLICATES=rename
>       - TELEGRAM_DAEMON_BOT=xxxxxxxxxxxxxxx
> #      - TELEGRAM_DAEMON_WORKERS=4
>     volumes:
>       - downloads:/downloads
>       - sessions:/session
>     restart: unless-stopped
>     labels:
>       - io.portainer.accesscontrol.public
>     logging:
>       options:
>         max-size: 1m
> volumes:
>     sessions:
>     downloads:
> ```
> 
> thank you very Much for your time and effort. it seems that it works. in the logs i can see just this line
> 
> `WARNING/2023-11-29 09:51:14,578]telethon.network.mtprotosender:Attempt 1 at connecting failed: TimeoutError: `
> 
> but when i send a file to my channel i get this message: `Error: 'Message' object has no attribute 'destination'`

**Comment by Nyaran** [comment]
@shahram7 what method are you using to send file to the channel? message link? group link? resend? I tried all methods, and I'm unable to reproduce that error. Can you provide me a step-by-step list to help you to solve the issue? The telegram channel where you are downloading from could be helpful (if is not a private channel, of course)

**Comment by shahram7** [comment]
HI Luis, I've always tested the daemon with sending a picture from gallery. I use a private channel for the downloader daemon.
[Screen_Recording_20231201_092946_Telegram.zip](https://github.com/Nyaran/telegram-download-daemon-ng/files/13522900/Screen_Recording_20231201_092946_Telegram.zip)

**Comment by Nyaran** [comment]
Oh, I see...

Working on it, thanks for the report!

**Comment by Nyaran** [comment]
Please try with `1.0.0-beta.7`

```shell
docker pull nyaran/telegram-download-daemon-ng:1.0.0-beta.7
```

**Comment by Nyaran** [comment]
Sorry, but unable to reproduce, I send many kind of files (mp4, mkv, iso, zip) with different size (6MB, 360MB, 450MB, 600MB and 1,5GB), and the videos tried as normal file and as media file and everything works

The file is uploaded to Telegram properly? Remember that first it will be uploaded to Telegram servers before the message is ready to be read by the bot.

If you can provide more info about the kind of file you are using, I could be able to reproduce the error
 - Type
 - Size
 - Name (replace sensitive information)

**Comment by Nyaran** [comment]
Hi! Sorry for my late response.

About the first messages, is about Telegram closing the connection, I'll try to check if we are making too many connections, anyway, is a warning message, so, if you are not having problems, you can ignore it.

About the second message, that is just the stacktrace, pointing the place in code when the error occurs, but not the error itself, There are line around that could be related, can you paste that lines too?

Lastly, to understand better your use case. You are in a channel, where a bot sends files, and you want to download that files? Be sure that you, or the account or bot you are setting up for the daemon, are joined to the group

**Comment by Nyaran** [comment]
Hi,

that last error seems the same that #55, closing this issue, as the original issue was resolved
