### ISSUE TITLE
The channel specified is private and you lack permission to access it. 

### ISSUE THREAD

**Issue by mjhassan1** [Nyaran/telegram-download-daemon-ng#47]
Getting below error, The channel specified is private and you lack permission to access it. Another reason may be that you were banned from it (caused by GetMessagesRequest)
All the users on the channel are administrator, still getting the above error

**Comment by Nyaran** [comment]
Hi,

the user you have configured for the daemon is your own user or a bot? In case is a bot, the bot itself should be in the channel too.

If is not the case, can you share with me the config of the channel? Not the channel itself, things like permissions, type of content you are trying to download, etc, also I need details about how you are running the daemon, with that I should be able to reproduce the scenario.

**Comment by Nyaran** [comment]
No response received, closing the issue.

If you still have any issue, feel free to open a new ticket.
